name: Upload Prebuilt Zip (Client)

on:
  push:
    paths:
      - 'CookiesClient/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create CookiesClient Zip
        run: |
          sudo apt-get install zip
          cd CookiesClient
          zip -r ../CookiesClient.zip icon.png manifest.json README.md BepInEx CHANGELOG.md
      - id: pub
        uses: ./
        with:
          namespace: ChocolateCookies
          name: CookiesClient
          token: ${{ secrets.TS_KEY }}
          description: |
            🍪 A Client-Side Quality-of-Life modpack with a few extra tweaks.
          version: v1.${{ github.run_number }}.0
          community: lethal-company
          repo: thunderstore.io
          website: "https://creampies.wtf"
          categories: |
            clientside
            furniture
            tools
            mods
            modpacks
            misc
            audio
            bepinex
          # Check the correct format for dependencies in Thunderstore
          deps: |
            ChocolateCookies-CookiesClient-1.${{ github.run_number }}.0
          file: ./CookiesClient.zip
      - run: echo ${{ steps.pub.outputs.url }}
